version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: mail.example.com
    container_name: mail
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "110:110"
    volumes:
      - ./var/mail:/var/mail
      - ./var/mail-state:/var/mail-state
      - ./config/:/tmp/docker-mailserver/
      - ./ssl:/ssl:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - DMS_DEBUG=0
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/ssl/cert/public.crt
      - SSL_KEY_PATH=/ssl/private/private.key

    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
